/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as ResearchSlugRouteImport } from './routes/research/$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin/projects.$id'
import { Route as AuthenticatedAdminResearchIdRouteImport } from './routes/_authenticated/admin/research.$id'
import { Route as ApiPublicFilesSplatRouteImport } from './routes/api/public/files/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/admin/projects/$id',
    path: '/admin/projects/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResearchIdRoute =
  AuthenticatedAdminResearchIdRouteImport.update({
    id: '/admin/research/$id',
    path: '/admin/research/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFilesSplatRoute = ApiPublicFilesSplatRouteImport.update({
  id: '/api/public/files/$',
  path: '/api/public/files/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/resume': typeof ResumeRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/research/$id': typeof AuthenticatedAdminResearchIdRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/resume': typeof ResumeRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/research': typeof ResearchIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/research/$id': typeof AuthenticatedAdminResearchIdRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/resume': typeof ResumeRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/_authenticated/admin/research/$id': typeof AuthenticatedAdminResearchIdRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/resume'
    | '/projects/$slug'
    | '/research/$slug'
    | '/projects/'
    | '/research/'
    | '/admin/settings'
    | '/admin/'
    | '/admin/projects/$id'
    | '/admin/research/$id'
    | '/api/public/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/resume'
    | '/projects/$slug'
    | '/research/$slug'
    | '/projects'
    | '/research'
    | '/admin/settings'
    | '/admin'
    | '/admin/projects/$id'
    | '/admin/research/$id'
    | '/api/public/files/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/resume'
    | '/projects/$slug'
    | '/research/$slug'
    | '/projects/'
    | '/research/'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/projects/$id'
    | '/_authenticated/admin/research/$id'
    | '/api/public/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ResumeRoute: typeof ResumeRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ResearchSlugRoute: typeof ResearchSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  ApiPublicFilesSplatRoute: typeof ApiPublicFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects/$id': {
      id: '/_authenticated/admin/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/research/$id': {
      id: '/_authenticated/admin/research/$id'
      path: '/admin/research/$id'
      fullPath: '/admin/research/$id'
      preLoaderRoute: typeof AuthenticatedAdminResearchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/files/$': {
      id: '/api/public/files/$'
      path: '/api/public/files/$'
      fullPath: '/api/public/files/$'
      preLoaderRoute: typeof ApiPublicFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
  AuthenticatedAdminResearchIdRoute: typeof AuthenticatedAdminResearchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
  AuthenticatedAdminResearchIdRoute: AuthenticatedAdminResearchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ResumeRoute: ResumeRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ResearchSlugRoute: ResearchSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  ApiPublicFilesSplatRoute: ApiPublicFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
